<?php

declare(strict_types=1);

namespace Shennawy\AiSeeder\Agents;

use Illuminate\Contracts\JsonSchema\JsonSchema;
use Illuminate\JsonSchema\Types\StringType;
use Illuminate\JsonSchema\Types\Type;
use Laravel\Ai\Contracts\Agent;
use Laravel\Ai\Contracts\HasStructuredOutput;
use Laravel\Ai\Contracts\HasTools;
use Laravel\Ai\Promptable;

class SeederAgent implements Agent, HasStructuredOutput, HasTools
{
    use Promptable;

    public function __construct(
        private readonly string $schemaDescription,
        private readonly int $count,
        /** @var array<string, array<string, mixed>> */
        private readonly array $columnDefinitions,
        private readonly string $language = 'en',
    ) {}

    /**
     * Get the instructions that the agent should follow.
     */
    public function instructions(): string
    {
        $baseInstructions = <<<'INSTRUCTIONS'
        You are a strict data generator. You MUST output ONLY valid JSON. Do not wrap the JSON in markdown blocks. Do not add any conversational text before or after the JSON.

        You are a database seeder AI. Your ONLY job is to generate realistic, context-aware dummy data for database tables.

        STRICT RULES:
        1. Return EXACTLY the number of rows requested — no more, no less.
        2. Every value MUST match the column's data type precisely.
        3. For unique columns, every generated value MUST be unique across all rows.
        4. For nullable columns, you MAY occasionally return null (roughly 10-20% of the time).
        5. Generate realistic, contextually appropriate data — names should look like names, emails like emails, etc.
        6. Do NOT include primary key, password, foreign key, or timestamp columns (created_at, updated_at, deleted_at) in the output — they are generated by the application.
        7. Do NOT wrap output in markdown. Return only the structured JSON.
        8. For JSON columns, you MUST return a valid JSON structure. If the column name implies a list (plural nouns like objectives, prerequisites, keywords, tags, skills), return a flat JSON Array like ["item1", "item2"]. If it implies structured/key-value data (content, conditions, settings, metadata), return a JSON Object like {"key": "value"}. NEVER return a plain string for JSON columns.
        9. For columns with a MAX LENGTH constraint, your value MUST NOT exceed that character limit. For example, a column with MAX 2 chars should get values like "en", "ar", "fr" — NOT "English".
        10. For ENUM columns, you MUST select ONLY from the listed allowed values. Do NOT invent new values.
        11. CRITICAL JSON STRUCTURE RULE: For list-like JSON columns (plural names like objectives, tags, keywords), ALWAYS return a flat Array ["a","b","c"]. For key-value JSON columns (content, conditions, settings) or when validation rules use dot-notation sub-keys, ALWAYS return an Object {"key":"value"}. NEVER output a flat sequential array of alternating keys and values like ["key","value","key2","value2"].
        12. CRITICAL DATETIME RULE: For any date, datetime, or timestamp columns, you MUST format dates exactly as 'YYYY-MM-DD HH:MM:SS' (e.g., '2024-01-15 10:00:00'). DO NOT use ISO 8601 format with 'T' or 'Z' — MySQL will reject it. Always use spaces between date and time components.
        INSTRUCTIONS;

        $languageRule = $this->buildLanguageRule();

        if ($languageRule !== '') {
            return $baseInstructions."\n".$languageRule;
        }

        return $baseInstructions;
    }

    /**
     * Get the tools available to the agent.
     *
     * @return array<int, mixed>
     */
    public function tools(): iterable
    {
        return [];
    }

    /**
     * Get the agent's structured output schema definition.
     *
     * Cross-provider compatible (OpenAI, Anthropic, Gemini, Ollama):
     * - No `additionalProperties` key (Gemini rejects it).
     * - No `nullable()` calls (Gemini rejects type arrays like ["string", "null"]).
     * - Nullability is enforced via the column description and system instructions.
     *
     * @return array<string, Type>
     */
    public function schema(JsonSchema $schema): array
    {
        $rowProperties = [];

        foreach ($this->columnDefinitions as $columnName => $definition) {
            $type = $this->mapColumnToSchemaType($schema, $definition, $columnName);

            // Do NOT call ->nullable() — Gemini rejects type: ["string", "null"].
            // Instead, nullability is communicated via the description text
            // and the system instruction rule #5 ("you MAY occasionally return null").

            $type = $type->required();

            // Build a description that merges:
            // 1. The column definition's description (from SchemaAnalyzer)
            // 2. The type-level description (e.g., JSON formatting rules from mapColumnToSchemaType)
            // 3. Nullability hint
            $descriptionParts = [];

            // Capture any description already set by mapColumnToSchemaType (e.g., JSON formatting rules)
            $existingDescription = (fn () => $this->description ?? '')->call($type);

            if (! empty($definition['description'])) {
                $descriptionParts[] = $definition['description'];
            }

            if ($existingDescription !== '' && ($definition['description'] ?? '') !== $existingDescription) {
                $descriptionParts[] = $existingDescription;
            }

            if ($definition['nullable'] ?? false) {
                $descriptionParts[] = 'This column is NULLABLE — you may return null for some rows.';
            }

            $finalDescription = implode('. ', array_map(fn (string $s) => rtrim($s, '. '), $descriptionParts));

            if ($finalDescription !== '') {
                $type = $type->description($finalDescription);
            }

            $rowProperties[$columnName] = $type;
        }

        return [
            'rows' => $schema->array()
                ->items($schema->object($rowProperties))
                ->min($this->count)
                ->max($this->count)
                ->required(),
        ];
    }

    /**
     * Map a database column type to a JsonSchema type.
     */
    private function mapColumnToSchemaType(JsonSchema $schema, array $definition, string $columnName = ''): Type
    {
        // JSON columns are mapped as `string` in the structured schema.
        // Using `array()->items(string())` would force the AI to always output
        // a flat sequential array `["a","b"]` — but many JSON columns need
        // a key-value object `{"key":"value"}`.  By using `string()` we let
        // the description and system instructions guide the AI to return
        // the correct JSON structure (array or object) as a string value.
        if ($definition['is_json'] ?? false) {
            $name = strtolower($columnName);
            $listPatterns = ['objectives', 'prerequisites', 'keywords', 'tags', 'skills', 'features', 'items', 'categories', 'roles', 'permissions', 'images', 'attachments', 'links', 'recipients', 'emails', 'phones', 'languages', 'topics', 'benefits', 'requirements', 'highlights', 'amenities', 'options'];

            if (in_array($name, $listPatterns, true) || str_ends_with($name, 's')) {
                return $schema->string()
                    ->description(
                        'JSON COLUMN (LIST) — you MUST return a flat JSON Array of strings like ["item1","item2","item3"]. '
                        .'Do NOT return a JSON Object for this column. Do NOT use alternating key-value arrays.',
                    );
            }

            return $schema->string()
                ->description(
                    'JSON COLUMN (OBJECT) — you MUST return a valid JSON Object like {"key":"value"}. '
                    .'Do NOT return a flat array. Use {} for structured key-value data.',
                );
        }

        $type = $definition['type'] ?? 'string';

        $result = match (true) {
            in_array($type, ['integer', 'bigint', 'smallint', 'tinyint', 'mediumint', 'int'], true) => $schema->integer(),
            in_array($type, ['float', 'double', 'decimal', 'real', 'numeric'], true) => $schema->number(),
            in_array($type, ['boolean', 'bool'], true) => $schema->boolean(),
            default => $schema->string(),
        };

        // Enforce max length on string types at the schema level.
        // ENUM constraints are enforced via the column description text
        // because the Laravel JSON Schema API does not have an enum() method.
        $maxLength = $definition['max_length'] ?? null;

        if ($maxLength !== null && $result instanceof StringType) {
            $result = $result->max($maxLength);
        }

        return $result;
    }

    /**
     * Build a language enforcement rule for the system instructions.
     *
     * Supports any single language code or comma-separated list.
     */
    private function buildLanguageRule(): string
    {
        $languages = array_values(array_filter(
            array_map('trim', explode(',', $this->language)),
            fn (string $l): bool => $l !== '',
        ));

        if (empty($languages)) {
            return '';
        }

        if (count($languages) === 1 && strtolower($languages[0]) === 'en') {
            return '';
        }

        if (count($languages) === 1) {
            $lang = $languages[0];

            return <<<RULE
        12. LANGUAGE: All generated text for human-readable string/text columns MUST be in {$lang}. Use authentic {$lang} names, titles, and content. Only emails, URLs, timestamps, and IDs may use Latin characters.
        RULE;
        }

        $langList = implode(', ', $languages);

        return <<<RULE
        12. LANGUAGE: Generate a realistic mix of {$langList} text. Distribute the languages naturally across rows to simulate a multi-lingual dataset. Emails, URLs, timestamps, and IDs always use Latin characters.
        RULE;
    }
}
